main: de.jumpdrive.customtime.CustomTimeMain
name: CustomTime
version: 1.0
api-version: 1.17
author: lucas
description: With this plugin it is possible to configure the duration of day and night on your Spigot Server
commands:
  customtime:
    description: Customtime command
    permission: customtime.admin
    permission-message: You do not have permission!
    usage: /<command> [on|off|help]